In [2]:
# Reference - https://www.youtube.com/watch?v=GB9ByFAIAH4&t=9s

import numpy as np

In [8]:
a = np.array([1,2,3])
# a = np.array([1,2,3],dtype = ' int32')
a

array([1, 2, 3])

In [18]:
b = np.array([[9.0,7.4,5.0],[4.0,3.0,7.6]])
b

array([[9. , 7.4, 5. ],
       [4. , 3. , 7.6]])

In [22]:
# get Dimention
a.ndim


1

In [21]:
b.ndim

2

In [23]:
#get shape/size
b.shape

(2, 3)

In [24]:
#get type
a.dtype

dtype('int64')

In [26]:
b.dtype

dtype('float64')

In [27]:
# get size

a.itemsize

8

In [30]:
# get total size 
a.size * a.itemsize

#or

a.nbytes

24

### Accessing/changing specific element,rows,columns,etc

In [31]:

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [34]:
#get specific element[r,c]

a[1,5]

# or

a[1,-2]

13

In [36]:
# get specific rows

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [40]:
# get specific column

a[:,0]

array([1, 8])

In [41]:
a[:,3]

array([ 4, 11])

In [45]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

# or

a[0,1:-1:2]

array([2, 4, 6])

In [48]:
# change elements

a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [52]:
# make 2nd colunm as 5
a[:,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [54]:
a[:,2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

###  3 D Example

In [55]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
# Get specific element (work outside in)

b[0,1,1]

4

In [57]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [59]:
# replace

b[:,1,:] = [[9,9],[6,6]]

b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [6, 6]]])

### Initializing Different Types of Arrays

In [60]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [62]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [63]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [64]:
# Any Random decimal numbers
np.random.rand(4,2)

array([[0.55644877, 0.39151185],
       [0.64270548, 0.81729847],
       [0.99092909, 0.38095473],
       [0.67056426, 0.31445873]])

In [66]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

#np.random.randint(3,8, size=(3,3))

array([[ 0,  1,  6],
       [ 5, -2,  2],
       [ 2,  4,  7]])

In [67]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [69]:
# Make your specific pattern of array

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

#output[1:-1,1:-1] = z
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [70]:
## Copy arrays (Be carefull)

a= np.array([1,2,3])
b=a
b


array([1, 2, 3])

In [72]:
b[0] = 100
b


array([100,   2,   3])

In [74]:
a   # problem here (for this use copy function)

array([100,   2,   3])

In [85]:
a = np.array([4,5,6])
b = a.copy()
b[1] = 100
b

array([  4, 100,   6])

In [84]:
a


array([4, 5, 6])

## Mathematics

In [86]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [87]:
a + 2
#a += 2

array([3, 4, 5, 6])

In [88]:
a - 2

array([-1,  0,  1,  2])

In [89]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [90]:
a * 2

array([2, 4, 6, 8])

In [92]:
b = np.array([1,0,1,0])

a + b


array([2, 2, 4, 4])

In [93]:
a ** 2

array([ 1,  4,  9, 16])

In [94]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [95]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)


### Linear algebra

In [96]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # here a * b will not work becoz of diff sizes

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [98]:

# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [97]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [99]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:

np.min(stats)

1

In [101]:

np.max(stats, axis=1)

array([3, 6])

In [102]:

np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays¶


In [108]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [105]:

# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous


### Load data from file

In [110]:
filedata = np.genfromtxt('Data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advanced Indexing¶


In [111]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [112]:
filedata >100

array([[False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [122]:
 filedata = filedata[filedata>50]
filedata

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [118]:
np.any(filedata > 50 ,axis = 0)

True

In [121]:
((filedata > 50) & (filedata < 100))

array([False,  True, False,  True,  True, False,  True,  True,  True])